apiVersion: apps/v1
kind: Deployment
metadata:
  name: qaz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qaz
  template:
    metadata:
      labels:
        app: qaz
    spec:
      containers:
      - image: okteto.dev/qaz:latest
        name: qaz
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "766bff62-8146-499c-8007-d044ad91be09"
        - name: Vless_Path
          value: "/vl111"
        - name: Vmess_UUID
          value: "766bff62-8146-499c-8007-d044ad91be09"
        - name: Vmess_Path
          value: "/vm222"
        - name: Share_Path
          value: "/v2link"
